#Task #1:

#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.

# Way_1 - works,but only if we are using new symbols. But if we try to add symbol which has used - we don't see them like new sybol

s = 'intern'
t = 'iinternSR'

setS = set(s)
setT = set(t)

resultSet = setT.difference(setS)
print("New symbol is:\n", ' \n'.join(resultSet))



# Way_2,using cycle FOR, is the better issue

s = 'intern'
t = 'iintternSR'

listS = list(s)
listT = list(t)
result = []

for letter in listT:
    if letter in listS:
        listS.remove(letter)
    else:
        result.append(letter)

print("New symbol is:\n", ' \n'.join(result))
